# DNS provider settings
[dns]
provider = "cloudflare" # options: cloudflare, gcp, route53

[dns.cloudflare]
api_key = "API_KEY"

[dns.gcp]
project = "project"

[dns.gcp.zone_mapping]
"certmagic_zone" = "gcp_zone"

[dns.route53]
"max-retries" = 5

# ACME settings
[acme]
email = "test@example.com"
acme_api_endpoint = "https://acme-staging-v02.api.letsencrypt.org/directory"
subscriber_agreement = false

[storage]
driver = "kubernetes" # options: kubernetes, filesystem,

[storage.filesystem]
path = "./deploy_tool_output"

[storage.kubernetes]
namespace = "prio-server"
